/**
 * TypeScript types for Supabase database schema
 * Generated from the database schema
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          clerk_user_id: string;
          email: string;
          username: string | null;
          full_name: string | null;
          snaptrade_user_id: string | null;
          snaptrade_user_secret: string | null;
          role: 'leader' | 'follower' | 'both' | 'admin';
          bio: string | null;
          strategy_description: string | null;
          max_followers: number;
          subscription_fee: number;
          is_verified: boolean;
          verification_date: string | null;
          verified_by_admin_id: string | null;
          has_performance_badge: boolean;
          has_consistency_badge: boolean;
          risk_score: number;
          volatility_score: number;
          leverage_score: number;
          transparency_score: number;
          total_trades: number;
          win_rate: number;
          total_roi: number;
          avg_return: number;
          sharpe_ratio: number;
          max_drawdown: number;
          total_followers: number;
          active_followers: number;
          trades_options: boolean;
          trades_0dte: boolean;
          uses_margin: boolean;
          avg_position_size: number;
          is_public: boolean;
          accepts_followers: boolean;
          created_at: string;
          updated_at: string;
          stats_updated_at: string | null;
        };
        Insert: {
          id?: string;
          clerk_user_id: string;
          email: string;
          username?: string | null;
          full_name?: string | null;
          snaptrade_user_id?: string | null;
          snaptrade_user_secret?: string | null;
          role?: 'leader' | 'follower' | 'both' | 'admin';
          bio?: string | null;
          strategy_description?: string | null;
          max_followers?: number;
          subscription_fee?: number;
          is_verified?: boolean;
          verification_date?: string | null;
          verified_by_admin_id?: string | null;
          has_performance_badge?: boolean;
          has_consistency_badge?: boolean;
          risk_score?: number;
          volatility_score?: number;
          leverage_score?: number;
          transparency_score?: number;
          total_trades?: number;
          win_rate?: number;
          total_roi?: number;
          avg_return?: number;
          sharpe_ratio?: number;
          max_drawdown?: number;
          total_followers?: number;
          active_followers?: number;
          trades_options?: boolean;
          trades_0dte?: boolean;
          uses_margin?: boolean;
          avg_position_size?: number;
          is_public?: boolean;
          accepts_followers?: boolean;
          created_at?: string;
          updated_at?: string;
          stats_updated_at?: string | null;
        };
        Update: {
          id?: string;
          clerk_user_id?: string;
          email?: string;
          username?: string | null;
          full_name?: string | null;
          snaptrade_user_id?: string | null;
          snaptrade_user_secret?: string | null;
          role?: 'leader' | 'follower' | 'both' | 'admin';
          bio?: string | null;
          strategy_description?: string | null;
          max_followers?: number;
          subscription_fee?: number;
          is_verified?: boolean;
          verification_date?: string | null;
          verified_by_admin_id?: string | null;
          has_performance_badge?: boolean;
          has_consistency_badge?: boolean;
          risk_score?: number;
          volatility_score?: number;
          leverage_score?: number;
          transparency_score?: number;
          total_trades?: number;
          win_rate?: number;
          total_roi?: number;
          avg_return?: number;
          sharpe_ratio?: number;
          max_drawdown?: number;
          total_followers?: number;
          active_followers?: number;
          trades_options?: boolean;
          trades_0dte?: boolean;
          uses_margin?: boolean;
          avg_position_size?: number;
          is_public?: boolean;
          accepts_followers?: boolean;
          created_at?: string;
          updated_at?: string;
          stats_updated_at?: string | null;
        };
      };
      brokerage_connections: {
        Row: {
          id: string;
          user_id: string;
          connection_id: string;
          account_id: string;
          brokerage_name: string;
          account_number: string | null;
          status: 'active' | 'broken' | 'deleted';
          account_type: string | null;
          balance: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          connection_id: string;
          account_id: string;
          brokerage_name: string;
          account_number?: string | null;
          status?: 'active' | 'broken' | 'deleted';
          account_type?: string | null;
          balance?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          connection_id?: string;
          account_id?: string;
          brokerage_name?: string;
          account_number?: string | null;
          status?: 'active' | 'broken' | 'deleted';
          account_type?: string | null;
          balance?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      copy_relationships: {
        Row: {
          id: string;
          leader_id: string;
          follower_id: string;
          position_sizing_method: 'proportional' | 'fixed_dollar' | 'fixed_shares' | 'risk_based' | 'multiplier';
          allocation_percent: number;
          fixed_dollar_amount: number | null;
          fixed_shares_amount: number | null;
          risk_percent: number | null;
          multiplier: number | null;
          max_position_size: number | null;
          auto_stop_loss_enabled: boolean;
          auto_stop_loss_percent: number | null;
          auto_stop_loss_type: string;
          trailing_stop_loss: boolean;
          auto_take_profit_enabled: boolean;
          auto_take_profit_percent: number | null;
          auto_take_profit_type: string;
          scale_out_enabled: boolean;
          scale_out_percentage: number | null;
          mirror_exits: boolean;
          stop_loss_percent: number | null;
          filter_by_market_cap: boolean;
          min_market_cap: number | null;
          max_market_cap: number | null;
          filter_by_price: boolean;
          min_stock_price: number | null;
          max_stock_price: number | null;
          filter_by_sector: boolean;
          allowed_sectors: string | null;
          blocked_sectors: string | null;
          skip_penny_stocks: boolean;
          skip_options: boolean;
          skip_0dte_options: boolean;
          skip_crypto: boolean;
          enable_exposure_limits: boolean;
          max_position_concentration: number | null;
          max_sector_concentration: number | null;
          max_open_positions: number | null;
          max_daily_trades: number | null;
          max_daily_volume: number | null;
          require_diversification: boolean;
          min_positions: number;
          status: 'active' | 'paused' | 'stopped';
          total_trades_copied: number;
          total_profit_loss: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          leader_id: string;
          follower_id: string;
          position_sizing_method?: 'proportional' | 'fixed_dollar' | 'fixed_shares' | 'risk_based' | 'multiplier';
          allocation_percent?: number;
          fixed_dollar_amount?: number | null;
          fixed_shares_amount?: number | null;
          risk_percent?: number | null;
          multiplier?: number | null;
          max_position_size?: number | null;
          auto_stop_loss_enabled?: boolean;
          auto_stop_loss_percent?: number | null;
          auto_stop_loss_type?: string;
          trailing_stop_loss?: boolean;
          auto_take_profit_enabled?: boolean;
          auto_take_profit_percent?: number | null;
          auto_take_profit_type?: string;
          scale_out_enabled?: boolean;
          scale_out_percentage?: number | null;
          mirror_exits?: boolean;
          stop_loss_percent?: number | null;
          filter_by_market_cap?: boolean;
          min_market_cap?: number | null;
          max_market_cap?: number | null;
          filter_by_price?: boolean;
          min_stock_price?: number | null;
          max_stock_price?: number | null;
          filter_by_sector?: boolean;
          allowed_sectors?: string | null;
          blocked_sectors?: string | null;
          skip_penny_stocks?: boolean;
          skip_options?: boolean;
          skip_0dte_options?: boolean;
          skip_crypto?: boolean;
          enable_exposure_limits?: boolean;
          max_position_concentration?: number | null;
          max_sector_concentration?: number | null;
          max_open_positions?: number | null;
          max_daily_trades?: number | null;
          max_daily_volume?: number | null;
          require_diversification?: boolean;
          min_positions?: number;
          status?: 'active' | 'paused' | 'stopped';
          total_trades_copied?: number;
          total_profit_loss?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['copy_relationships']['Insert']>;
      };
      leader_trades: {
        Row: {
          id: string;
          leader_id: string;
          account_id: string;
          symbol: string;
          action: 'buy' | 'sell';
          quantity: number;
          price: number | null;
          order_type: string;
          asset_type: 'stock' | 'option' | 'etf' | 'crypto';
          option_type: 'call' | 'put' | null;
          strike_price: number | null;
          expiration_date: string | null;
          contracts: number | null;
          universal_symbol_id: string | null;
          order_id: string | null;
          stop_loss: number | null;
          take_profit: number | null;
          processed: boolean;
          is_exit: boolean;
          detected_at: string;
          executed_at: string | null;
        };
        Insert: {
          id?: string;
          leader_id: string;
          account_id: string;
          symbol: string;
          action: 'buy' | 'sell';
          quantity: number;
          price?: number | null;
          order_type?: string;
          asset_type?: 'stock' | 'option' | 'etf' | 'crypto';
          option_type?: 'call' | 'put' | null;
          strike_price?: number | null;
          expiration_date?: string | null;
          contracts?: number | null;
          universal_symbol_id?: string | null;
          order_id?: string | null;
          stop_loss?: number | null;
          take_profit?: number | null;
          processed?: boolean;
          is_exit?: boolean;
          detected_at?: string;
          executed_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['leader_trades']['Insert']>;
      };
      copy_executions: {
        Row: {
          id: string;
          trade_id: string;
          relationship_id: string;
          follower_id: string;
          symbol: string;
          action: 'buy' | 'sell';
          quantity: number;
          executed_price: number | null;
          asset_type: 'stock' | 'option' | 'etf' | 'crypto';
          option_type: 'call' | 'put' | null;
          strike_price: number | null;
          expiration_date: string | null;
          contracts: number | null;
          stop_loss_order_id: string | null;
          stop_loss_price: number | null;
          take_profit_order_id: string | null;
          take_profit_price: number | null;
          status: 'pending' | 'success' | 'failed' | 'skipped';
          error_message: string | null;
          order_id: string | null;
          account_id: string;
          created_at: string;
          executed_at: string | null;
        };
        Insert: {
          id?: string;
          trade_id: string;
          relationship_id: string;
          follower_id: string;
          symbol: string;
          action: 'buy' | 'sell';
          quantity: number;
          executed_price?: number | null;
          asset_type?: 'stock' | 'option' | 'etf' | 'crypto';
          option_type?: 'call' | 'put' | null;
          strike_price?: number | null;
          expiration_date?: string | null;
          contracts?: number | null;
          stop_loss_order_id?: string | null;
          stop_loss_price?: number | null;
          take_profit_order_id?: string | null;
          take_profit_price?: number | null;
          status?: 'pending' | 'success' | 'failed' | 'skipped';
          error_message?: string | null;
          order_id?: string | null;
          account_id: string;
          created_at?: string;
          executed_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['copy_executions']['Insert']>;
      };
      leader_stats: {
        Row: {
          id: string;
          leader_id: string;
          follower_count: number;
          total_trades: number;
          winning_trades: number;
          losing_trades: number;
          win_rate: number;
          roi_1m: number;
          roi_3m: number;
          roi_6m: number;
          roi_1y: number;
          roi_all_time: number;
          avg_trade_duration_hours: number;
          max_drawdown: number;
          sharpe_ratio: number;
          sortino_ratio: number;
          portfolio_value: number;
          last_trade_date: string | null;
          calculated_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          leader_id: string;
          follower_count?: number;
          total_trades?: number;
          winning_trades?: number;
          losing_trades?: number;
          win_rate?: number;
          roi_1m?: number;
          roi_3m?: number;
          roi_6m?: number;
          roi_1y?: number;
          roi_all_time?: number;
          avg_trade_duration_hours?: number;
          max_drawdown?: number;
          sharpe_ratio?: number;
          sortino_ratio?: number;
          portfolio_value?: number;
          last_trade_date?: string | null;
          calculated_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['leader_stats']['Insert']>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'leader' | 'follower' | 'both' | 'admin';
      connection_status: 'active' | 'broken' | 'deleted';
      copy_relationship_status: 'active' | 'paused' | 'stopped';
      trade_action: 'buy' | 'sell';
      execution_status: 'pending' | 'success' | 'failed' | 'skipped';
      position_sizing_method: 'proportional' | 'fixed_dollar' | 'fixed_shares' | 'risk_based' | 'multiplier';
      asset_type: 'stock' | 'option' | 'etf' | 'crypto';
      option_type: 'call' | 'put';
    };
  };
}
